### ISSUE TITLE
ADD index.html and data.sh

### ISSUE THREAD

**Issue by pepoangel** [hashicorp/learn-terraform#32]
resource "aws_instance" "web" {
  ami           = data.aws_ami.ubuntu.id
  instance_type = "t2.micro"
  key_name      = aws_key_pair.deployer.key_name
  user_data    = file("data.sh")
  vpc_security_group_ids = [
    aws_security_group.allow_ssh.id,
    aws_security_group.allow_http.id
  ]
I have the data.sh file in the repository, and I also have the index.html file. When Terraform runs, it applies the data.sh file, but for some reason, it doesn't apply the index.html file that is located in the same repository. Do I need to add something else for it to also take into account the index.html file?
#! /bin/bash
sudo apt update
sudo apt install -y nginx
sudo rm /var/www/html/index.nginx-debian.html
sudo cp index.html /var/www/html/
sudo systemctl start nginx
sudo systemctl enable nginx

**Comment by ritsok** [comment]
Hi @pepoangel, sorry for the late reply to the issue. Hope you found a solution by now, but for anyone else who comes across this -- you'll need to update the user data script to source the file or file contents directly, or (as a last resort), use a [provisioner](https://developer.hashicorp.com/terraform/language/resources/provisioners/file).
